---
- hosts: all
  become: true

  pre_tasks:
    - name: create jenkins group
      group:
        name: jenkins
        state: present
        gid: 1001

    - name: create jenkins user
      user:
        name: jenkins
        state: present
        uid: 1001
        group: jenkins
        home: /var/lib/jenkins
        system: yes

    - name: fix resolv.conf
      lineinfile:
        path: /etc/resolv.conf
        state: absent
        line: "search example.com"

  vars:
    java_packages:
      - java-1.8.0-openjdk
    jenkins_plugins:
      - ansible
      - ansicolor
      - build-timeout
      - credentials-binding
      - email-ext
      - envinject
      - ghprb
      - git
      - github
      - htmlpublisher
      - ircbot
      - jenkins-multijob-plugin
      - job-dsl
      - parameterized-trigger
      - pipeline-githubnotify-step
      - progress-bar-column-plugin
      - ssh-slaves
      #- uno-choice  ## now vendored from jenkins-plugins
      - workflow-aggregator
      - ws-cleanup
    CANDLEPIN_JENKINS_GITHUB_ORG: candlepin
  roles:
    - geerlingguy.jenkins

  tasks:
    - name: copy vendored plugins
      synchronize:
        src: "jenkins-plugins/"
        dest: "/var/lib/jenkins/plugins/"

    - name: set perms on vendored plugins
      file:
        dest: /var/lib/jenkins/plugins
        owner: jenkins
        group: jenkins
        mode: 0755
        recurse: yes

    - name: copy init.groovy
      copy:
        src: init.groovy
        dest: /var/lib/jenkins/
        owner: jenkins
        group: jenkins
        mode: 0755

    - name: disable mail relay
      lineinfile: dest=/etc/postfix/main.cf line="default_transport = local:$myhostname"
      notify: reload postfix config

    - name: template development seed job
      template: src=templates/seed.groovy.j2 dest=/vagrant/ansible/seed.groovy

    - name: (re)generate development seed job
      command: ./gradlew rest -Dpattern=ansible/seed.groovy -DbaseUrl=http://{{ jenkins_hostname }}:{{ jenkins_http_port }}/ -Dusername={{ jenkins_admin_username }} -Dpassword={{ jenkins_admin_password }} chdir=/vagrant
      tags:
        - skip_ansible_lint

  handlers:
    - name: reload postfix config
      service: name=postfix state=reloaded

- hosts: all
  become: true
  vars:
    jenkins_dummy_configs:
      - candlepinPerformanceInventory

  tasks:
    - name: Wait for Jenkins to start up before proceeding.
      shell: "curl -D - --silent --max-time 5 http://localhost:8080/cli/"
      register: result
      until: (result.stdout.find("403 Forbidden") != -1) or (result.stdout.find("200 OK") != -1) and (result.stdout.find("Please wait while") == -1)
      retries: "60"
      delay: "5"
      changed_when: false
