---
- hosts: all
  become: true
  vars:
    jenkins_plugins:
      - ansible
      - ansicolor
      - config-file-provider
      - email-ext
      - envinject
      - ghprb
      - git
      - github
      - htmlpublisher
      - ircbot
      - job-dsl
      - parameterized-trigger
      - uno-choice
      - workflow-aggregator
      - ws-cleanup
    CANDLEPIN_JENKINS_GITHUB_ORG: candlepin
    jenkins_dummy_configs:
      - candlepinPerformanceInventory
  roles:
    - geerlingguy.jenkins

  tasks:
    - name: disable mail relay
      lineinfile: dest=/etc/postfix/main.cf line="default_transport = local:$myhostname"
      notify: reload postfix config

    - name: template development seed job
      template: src=templates/seed.groovy.j2 dest=/vagrant/ansible/seed.groovy

    - name: (re)generate development seed job
      command: ./gradlew rest -Dpattern=ansible/seed.groovy -DbaseUrl=http://{{ jenkins_hostname }}:{{ jenkins_http_port }}/ -Dusername={{ jenkins_admin_username }} -Dpassword={{ jenkins_admin_password }} chdir=/vagrant
      tags:
        - skip_ansible_lint

    - name: create dummy config files
      shell: >
        echo "javaposse.jobdsl.plugin.ConfigFileProviderHelper.findConfigProvider(javaposse.jobdsl.dsl.ConfigFileType.Custom).save(new org.jenkinsci.plugins.configfiles.custom.CustomConfig('{{ item }}', '{{ item }}', 'dummy file', ''))" |
        java -jar {{ jenkins_jar_location }}
        -s http://{{ jenkins_hostname }}:{{ jenkins_http_port }}{{ jenkins_url_prefix | default('') }}/
        groovy =
        --username {{ jenkins_admin_username }} --password {{ jenkins_admin_password }}
      with_items: "{{ jenkins_dummy_configs }}"
      tags:
        - dummyconfig

  handlers:
    - name: reload postfix config
      service: name=postfix state=reloaded
